# Generated by Django 3.2.9 on 2021-12-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('busy', models.BooleanField(default=False, verbose_name='繁忙')),
                ('current_step', models.IntegerField(default=3, verbose_name='当前步骤')),
                ('dataset', models.FileField(upload_to='dataset', verbose_name='数据集')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('is_datetime', models.BooleanField(default=False, verbose_name='时间?')),
                ('is_user_id', models.BooleanField(default=False, verbose_name='用户编号?')),
                ('is_interaction', models.BooleanField(default=False, verbose_name='互动指标?')),
                ('is_text', models.BooleanField(default=False, verbose_name='正文?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '列',
                'verbose_name_plural': '列',
            },
        ),
        migrations.CreateModel(
            name='AsyncErrorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('current_step', models.IntegerField(default=3, verbose_name='创建步骤')),
                ('error_message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '异步错误',
                'verbose_name_plural': '异步错误',
            },
        ),
    ]
