# Generated by Django 3.2.9 on 2021-12-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20211204_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='is_interaction',
        ),
        migrations.RemoveField(
            model_name='column',
            name='is_text',
        ),
        migrations.RemoveField(
            model_name='column',
            name='is_user_id',
        ),
        migrations.AddField(
            model_name='column',
            name='is_dmu',
            field=models.BooleanField(default=False, verbose_name='DMU?'),
        ),
        migrations.AddField(
            model_name='column',
            name='is_input',
            field=models.BooleanField(default=False, verbose_name='投入?'),
        ),
        migrations.AddField(
            model_name='column',
            name='is_output',
            field=models.BooleanField(default=False, verbose_name='产出?'),
        ),
        migrations.AlterField(
            model_name='asyncerrormessage',
            name='current_step',
            field=models.IntegerField(verbose_name='发生在步骤'),
        ),
    ]
