# Generated by Django 3.2.9 on 2021-12-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20211205_0041'),
        ('BHT_ARIMA_RUNTIME', '0002_downloadcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcache',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DownloadTask1', to='task_manager.task', verbose_name='任务'),
        ),
    ]
