# Generated by Django 3.2.9 on 2021-12-05 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0003_auto_20211205_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeaResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.FileField(upload_to='evaluation')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
        ),
    ]
