# Generated by Django 3.2.9 on 2021-12-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20211205_0041'),
        ('DEA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dearesults',
            options={'verbose_name': '绩效评价结果', 'verbose_name_plural': '绩效评价结果'},
        ),
        migrations.AddField(
            model_name='dearesults',
            name='dmu_list',
            field=models.TextField(blank=True, verbose_name='环境保护机构'),
        ),
        migrations.AlterField(
            model_name='dearesults',
            name='evaluation',
            field=models.FileField(upload_to='evaluation', verbose_name='绩效评价'),
        ),
        migrations.AlterField(
            model_name='dearesults',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task', verbose_name='任务'),
        ),
    ]
