# Generated by Django 3.2.9 on 2021-12-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20211205_0041'),
        ('DEA', '0002_auto_20211205_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_file', models.FileField(upload_to='download_cache', verbose_name='下载缓存')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DownloadTask2', to='task_manager.task', verbose_name='任务')),
            ],
        ),
    ]
